# ============================================================================
# dbt Profile Configuration - SECURE VERSION
# ============================================================================
# ⚠️ NEVER commit credentials to Git!
# ⚠️ Use environment variables or Snowflake secrets instead
# ============================================================================

atp_denmark:
  target: dev
  outputs:
    dev:
      type: snowflake
      # Account identifier
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'UTYEYAD-XT83149') }}"
      
      # User credentials - NEVER hardcode!
      user: "{{ env_var('SNOWFLAKE_USER', 'admin') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"  # ⚠️ REQUIRED - must be set
      
      # Connection details
      role: ATP_ADMIN
      warehouse: ATP_ETL_WH
      database: ATP_PENSION
      schema: PUBLIC
      
      # Performance settings
      threads: 4
      client_session_keep_alive: True
      
      # Query tags for monitoring
      query_tag: "dbt_atp_denmark"

# ============================================================================
# Environment Variables Setup
# ============================================================================
# 
# Set these in your environment BEFORE running dbt:
# 
# macOS/Linux:
#   export SNOWFLAKE_ACCOUNT="UTYEYAD-XT83149"
#   export SNOWFLAKE_USER="admin"
#   export SNOWFLAKE_PASSWORD="your_password_here"
# 
# Windows (PowerShell):
#   $env:SNOWFLAKE_ACCOUNT = "UTYEYAD-XT83149"
#   $env:SNOWFLAKE_USER = "admin"
#   $env:SNOWFLAKE_PASSWORD = "your_password_here"
# 
# Windows (CMD):
#   set SNOWFLAKE_ACCOUNT=UTYEYAD-XT83149
#   set SNOWFLAKE_USER=admin
#   set SNOWFLAKE_PASSWORD=your_password_here
# 
# ============================================================================
# Snowflake Workspaces (Native dbt)
# ============================================================================
# 
# When running in Snowflake Workspaces, credentials are automatically
# inherited from your Snowflake session. You can leave password empty
# or reference a Snowflake secret:
# 
# password: "{{ snowflake_secret('SECRETS.CREDENTIALS.dbt_snowflake_password') }}"
# 
# ============================================================================
# CI/CD (Azure DevOps, GitHub Actions)
# ============================================================================
# 
# Store credentials as pipeline secrets/variables:
# - SNOWFLAKE_ACCOUNT
# - SNOWFLAKE_USER  
# - SNOWFLAKE_PASSWORD
# 
# These will be automatically available as environment variables
# 
# ============================================================================
