version: 2

models:
  - name: applications_enriched
    description: |
      **Enriched housing benefit applications with member demographics**
      
      Combines housing benefit application data with member information for:
      - Application status tracking
      - Benefit calculation validation
      - Member demographic analysis
      - Approval/rejection trends
      
      **Source**: ATP_HOUSING_BENEFITS.RAW.APPLICATIONS
      **Refresh**: Incremental
      **Owner**: Housing Benefits Team
      
    columns:
      - name: application_id
        description: Unique identifier for each application
        tests:
          - unique
          - not_null
      
      - name: cpr_number
        description: Applicant's CPR number
        tests:
          - not_null
          - relationships:
              to: ref('members_clean')
              field: cpr_number
      
      - name: application_date
        description: Date application was submitted
        tests:
          - not_null
      
      - name: status
        description: Current application status
        tests:
          - not_null
          - accepted_values:
              values: ['Pending', 'Approved', 'Rejected', 'Under Review']
      
      - name: approval_date
        description: Date application was approved (if applicable)
      
      - name: annual_income
        description: Declared annual income (DKK)
        tests:
          - not_null
              min_value: 0
              max_value: 2000000
              severity: warn
      
      - name: monthly_rent
        description: Monthly rent amount (DKK)
        tests:
          - not_null
              min_value: 0
              max_value: 50000
              severity: warn
      
      - name: household_size
        description: Number of people in household
        tests:
          - not_null
              min_value: 1
              max_value: 20
              severity: warn
      
      - name: dwelling_type
        description: Type of dwelling
        tests:
          - accepted_values:
              values: ['Apartment', 'House', 'Room', 'Other']
      
      - name: dwelling_size_m2
        description: Dwelling size in square meters
        tests:
          - not_null
              min_value: 10
              max_value: 500
              severity: warn
      
      - name: calculated_benefit
        description: Calculated monthly benefit amount (DKK)
      
      - name: full_name
        description: Applicant's full name
      
      - name: age
        description: Applicant's age
      
      - name: city
        description: City of residence
      
      - name: dbt_updated_at
        description: Last dbt processing timestamp
        tests:
          - not_null

