-- ============================================================================
-- ATP Denmark - Role-Based Access Control (RBAC)
-- ============================================================================
-- Purpose: Create roles and grant appropriate permissions
-- Run As: ACCOUNTADMIN
-- Idempotent: Yes
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- ============================================================================
-- ROLES: Domain-based access control
-- ============================================================================

-- ATP Admin - Full access to all ATP resources
CREATE ROLE IF NOT EXISTS ATP_ADMIN;
GRANT USAGE ON WAREHOUSE ATP_ETL_WH TO ROLE ATP_ADMIN;
GRANT USAGE ON WAREHOUSE ATP_BI_WH TO ROLE ATP_ADMIN;
GRANT USAGE ON WAREHOUSE ATP_COMPLIANCE_WH TO ROLE ATP_ADMIN;

-- Data Engineer - ETL and transformation work
CREATE ROLE IF NOT EXISTS ATP_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE ATP_ETL_WH TO ROLE ATP_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE ATP_BI_WH TO ROLE ATP_DATA_ENGINEER;

-- Analyst - Read-only access to SILVER and GOLD layers
CREATE ROLE IF NOT EXISTS ATP_ANALYST;
GRANT USAGE ON WAREHOUSE ATP_BI_WH TO ROLE ATP_ANALYST;

-- Compliance Officer - Audit and governance access
CREATE ROLE IF NOT EXISTS ATP_COMPLIANCE_OFFICER;
GRANT USAGE ON WAREHOUSE ATP_COMPLIANCE_WH TO ROLE ATP_COMPLIANCE_OFFICER;

-- ============================================================================
-- PENSION DATABASE PERMISSIONS
-- ============================================================================

-- ATP_ADMIN: Full access
GRANT USAGE ON DATABASE ATP_PENSION TO ROLE ATP_ADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ATP_PENSION TO ROLE ATP_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE ATP_PENSION TO ROLE ATP_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE ATP_PENSION TO ROLE ATP_ADMIN;

-- ATP_DATA_ENGINEER: Read/Write SILVER and GOLD
GRANT USAGE ON DATABASE ATP_PENSION TO ROLE ATP_DATA_ENGINEER;
GRANT USAGE ON SCHEMA ATP_PENSION.RAW TO ROLE ATP_DATA_ENGINEER;
GRANT USAGE ON SCHEMA ATP_PENSION.SILVER TO ROLE ATP_DATA_ENGINEER;
GRANT USAGE ON SCHEMA ATP_PENSION.GOLD TO ROLE ATP_DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA ATP_PENSION.RAW TO ROLE ATP_DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ATP_PENSION.SILVER TO ROLE ATP_DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ATP_PENSION.GOLD TO ROLE ATP_DATA_ENGINEER;

-- ATP_ANALYST: Read-only SILVER and GOLD
GRANT USAGE ON DATABASE ATP_PENSION TO ROLE ATP_ANALYST;
GRANT USAGE ON SCHEMA ATP_PENSION.SILVER TO ROLE ATP_ANALYST;
GRANT USAGE ON SCHEMA ATP_PENSION.GOLD TO ROLE ATP_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA ATP_PENSION.SILVER TO ROLE ATP_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA ATP_PENSION.GOLD TO ROLE ATP_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ATP_PENSION.SILVER TO ROLE ATP_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ATP_PENSION.GOLD TO ROLE ATP_ANALYST;

-- ============================================================================
-- HOUSING BENEFITS DATABASE PERMISSIONS
-- ============================================================================

-- Similar pattern for housing benefits
GRANT USAGE ON DATABASE ATP_HOUSING_BENEFITS TO ROLE ATP_ADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ATP_HOUSING_BENEFITS TO ROLE ATP_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE ATP_HOUSING_BENEFITS TO ROLE ATP_ADMIN;

GRANT USAGE ON DATABASE ATP_HOUSING_BENEFITS TO ROLE ATP_DATA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ATP_HOUSING_BENEFITS TO ROLE ATP_DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE ATP_HOUSING_BENEFITS TO ROLE ATP_DATA_ENGINEER;

GRANT USAGE ON DATABASE ATP_HOUSING_BENEFITS TO ROLE ATP_ANALYST;
GRANT USAGE ON SCHEMA ATP_HOUSING_BENEFITS.SILVER TO ROLE ATP_ANALYST;
GRANT USAGE ON SCHEMA ATP_HOUSING_BENEFITS.GOLD TO ROLE ATP_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA ATP_HOUSING_BENEFITS.SILVER TO ROLE ATP_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA ATP_HOUSING_BENEFITS.GOLD TO ROLE ATP_ANALYST;

-- ============================================================================
-- INTEGRATION DATABASE PERMISSIONS
-- ============================================================================

GRANT USAGE ON DATABASE ATP_INTEGRATION TO ROLE ATP_ADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ATP_INTEGRATION TO ROLE ATP_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE ATP_INTEGRATION TO ROLE ATP_ADMIN;

GRANT USAGE ON DATABASE ATP_INTEGRATION TO ROLE ATP_DATA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ATP_INTEGRATION TO ROLE ATP_DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN DATABASE ATP_INTEGRATION TO ROLE ATP_DATA_ENGINEER;

-- ============================================================================
-- GOVERNANCE DATABASE PERMISSIONS
-- ============================================================================

GRANT USAGE ON DATABASE ATP_GOVERNANCE TO ROLE ATP_COMPLIANCE_OFFICER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ATP_GOVERNANCE TO ROLE ATP_COMPLIANCE_OFFICER;
GRANT SELECT ON ALL TABLES IN DATABASE ATP_GOVERNANCE TO ROLE ATP_COMPLIANCE_OFFICER;

GRANT USAGE ON DATABASE ATP_GOVERNANCE TO ROLE ATP_ADMIN;
GRANT ALL ON SCHEMA ATP_GOVERNANCE.METADATA TO ROLE ATP_ADMIN;
GRANT ALL ON SCHEMA ATP_GOVERNANCE.GOVERNANCE TO ROLE ATP_ADMIN;

-- ============================================================================
-- ROLE HIERARCHY
-- ============================================================================

-- Grant roles to ACCOUNTADMIN
GRANT ROLE ATP_ADMIN TO ROLE ACCOUNTADMIN;
GRANT ROLE ATP_DATA_ENGINEER TO ROLE ACCOUNTADMIN;
GRANT ROLE ATP_ANALYST TO ROLE ACCOUNTADMIN;
GRANT ROLE ATP_COMPLIANCE_OFFICER TO ROLE ACCOUNTADMIN;

-- Role hierarchy (optional - uncomment if desired)
-- GRANT ROLE ATP_ANALYST TO ROLE ATP_DATA_ENGINEER;
-- GRANT ROLE ATP_DATA_ENGINEER TO ROLE ATP_ADMIN;

-- ============================================================================
-- SUMMARY
-- ============================================================================

SELECT 'Roles Created' AS status,
       '4 roles with domain-based permissions' AS configuration;

SHOW ROLES LIKE 'ATP_%';

